### PR TITLE
fix Update how output of matplotlib is shown

### PR DESCRIPTION
**Pull request by andresfelipemendez**
Pr to address this issue
https://github.com/Cheukting/pyscript-tutorial/issues/2

I don't know how to link the issue to the PR

### CODE REVIEW

**Comment by Cheukting** [comment]
Thank you very much! This is awesome! One little thing to ask, if you can update `viz_with_matplotlib.html` accordingly as well that would be great.

**Comment by andresfelipemendez** [comment]
yes, I'll send the update later today

**Comment by andresfelipemendez** [comment]
Updated, and corrected the instances I missed in my previous commit.

**Comment by Cheukting** [comment]
Thank you very much @andresfelipemendez Do you want to add your name a the bottom of the README.md? Something like:

```
Contributors: 
- <Your name> @andresfelipemendez
```

Let me know then I will merge :-)

**Comment by andresfelipemendez** [comment]
yeah sounds good, I added my name to the readme, thanks!

**Comment by Cheukting** [comment]
Thank you so much @andresfelipemendez Great Job!

**Pull request merged**
